In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
#random.rand()函数根据给定维度生成[0,1)之间的数据，包含0，不包含1
#random.randn()返回一组服从正态分布的随机值。

In [3]:
data

array([[ 0.63734512, -0.90568016, -1.04943753],
       [ 0.37737326, -0.40138305,  0.23537301]])

In [4]:
data * 10

array([[  6.37345122,  -9.05680158, -10.49437533],
       [  3.7737326 ,  -4.01383052,   2.35373011]])

In [5]:
data + data

array([[ 1.27469024, -1.81136032, -2.09887507],
       [ 0.75474652, -0.8027661 ,  0.47074602]])

In [6]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [6,7.5,8,0,1]

In [10]:
arr1 = np.array(data1)
#其中传入array中的对象可以是列表，元祖等类似数组的数据

In [11]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
#嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组：
data2 = [[1,2,3,4],[5,6,7,8]]

In [13]:
arr2 = np.array(data2)

In [14]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
#data2是列表的列表，NumPy数组arr2的两个维度的shape是从data2引入的。可以用属性ndim和shape验证
arr2.ndim
#ndim 返回数组的维度

2

In [16]:
arr2.shape
#返回2行4列

(2, 4)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [19]:
#除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
#numpy.empty(shape, dtype=float, order='C', *, like=None)，用来输出一个空数组  like：默认为numpy数组，可以根据你的需要更改数组类型 
np.empty((2,3,2))

array([[[9.18118198e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.92806822e-057]],

       [[7.87105026e-067, 4.74603097e+174],
        [3.89037025e-033, 1.43688434e-071],
        [3.96489330e-061, 3.93285404e-061]]])

In [24]:
#arange是Python内置函数range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])