In [1]:
#ndarry 的数据类型

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3],dtype=np.float64 )

In [4]:
arr2 = np.array([1,2,3],dtype= np.int32)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int32')

In [7]:
arr = np.array([1,2,3,4,5])

In [8]:
arr.dtype

dtype('int32')

In [9]:
#通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype

In [10]:
float_arr = arr.astype(np.float64)

In [11]:
float_arr.dtype

dtype('float64')

In [12]:
#在本例中，整数被转换成了浮点数。如果将浮点数转换成整数，则小数部分将会被截取删除
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [13]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [14]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [15]:
#如果某字符串数组表示的全是数字，也可以用astype将其转换为数值形式：

In [16]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [17]:
numeric_strings.astype(float)
#注意：使用numpy.string_类型时，一定要小心，因为NumPy的字符串数据是大小固定的，发生截取时，不会发出警告。pandas提供了更多非数值数据的便利的处理方法。

array([ 1.25, -9.6 , 42.  ])