In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]
#不包括8

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
#当你将一个标量值赋值给一个切片时（如arr[5:8]=12），该值会自动传播（也就说后面将会讲到的“广播”）到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上

In [9]:
arr_slice = arr[5:8]

In [10]:
arr_slice

array([12, 12, 12])

In [11]:
#当修改arr_slice中的值，变动也会体现在原始数组arr中：
arr_slice[1] = 12345

In [12]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [13]:
#切片[ : ]会给数组中的所有值赋值：
arr_slice[:] = 64

In [14]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [15]:
#在一个二维数组中，各索引位置上的元素不再是标量而是一维数组：

In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [17]:
arr2d[2]

array([7, 8, 9])

In [18]:
#因此，可以对各个元素进行递归访问，但这样需要做的事情有点多。你可以传入一个以逗号隔开的索引列表来选取单个元素。也就是说，下面两种方式是等价的：

In [19]:
arr2d[0][2]

3

In [20]:
arr2d[0,2]

3

In [21]:
#在多维数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）。因此，在2×2×3数组arr3d中：

In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [23]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d[0]
#arr3d[0]是一个2×3数组：

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#标量值和数组都可以被赋值给arr3d[0]：
old_values = arr3d[0].copy()

In [26]:
arr3d[0] =42

In [27]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0] = old_values

In [29]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
#arr3d[1,0]可以访问索引以(1,0)开头的那些值（以一维数组的形式返回）
arr3d[1, 0]

array([7, 8, 9])

In [31]:
#虽然是用两步进行索引的，表达式是相同的：
x = arr3d[1]

In [32]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
x[0]

array([7, 8, 9])

In [34]:
#注意，在上面所有这些选取数组子集的例子中，返回的数组都是视图。

# 切片索引

In [35]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [36]:
#ndarray的切片语法跟Python列表这样的一维对象差不多：
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [37]:
#对于之前的二维数组arr2d，其切片方式稍显不同：
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
 arr2d[:2, 1:]
#像这样进行切片时，只能得到相同维数的数组视图。通过将整数索引和切片混合，可以得到低维度的切片。

array([[2, 3],
       [5, 6]])

In [40]:
arr2d[1, :2]

array([4, 5])

In [41]:
arr2d[:2, 2]

array([3, 6])

In [42]:
#注意，“只有冒号”表示选取整个轴，因此你可以像下面这样只对高维轴进行切片：
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [43]:
#自然，对切片表达式的赋值操作也会被扩散到整个选区：
arr2d[:2, 1:] = 0

In [44]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# 布尔型索引

In [45]:
#来看这样一个例子，假设我们有一个用于存储数据的数组以及一个存储姓名的数组（含有重复项）。在这里，我将使用numpy.random中的randn函数生成一些正态分布的随机数据：

In [46]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [47]:
data = np.random.randn(7,4)
#这个函数的参数是数组的维度，返回一组服从正态分布的随机值。

In [48]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [49]:
data

array([[ 1.24165116,  0.91849097, -1.02645167,  0.44442646],
       [-0.05033314, -1.49198746, -1.89303973, -0.53393241],
       [ 0.51937743,  0.86376543, -0.04697297, -0.6856795 ],
       [-0.37949576, -1.02205427, -0.04506876,  1.13727669],
       [ 0.2385302 ,  0.35767876,  0.45193206, -0.49099526],
       [-0.58349494, -0.57655013, -0.82805041, -0.16917763],
       [-0.12459374, -0.92308631,  2.35621205,  0.22692394]])

In [50]:
#假设每个名字都对应data数组中的一行，而我们想要选出对应于名字"Bob"的所有行。跟算术运算一样，数组的比较运算（如==）也是矢量化的。因此，对names和字符串"Bob"的比较运算将会产生一个布尔型数组：
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [51]:
data[names == 'Bob']

array([[ 1.24165116,  0.91849097, -1.02645167,  0.44442646],
       [-0.37949576, -1.02205427, -0.04506876,  1.13727669]])

In [52]:
###如果布尔型数组的长度不对，布尔型选择就会出错，因此一定要小心。
###布尔型数组的长度必须跟被索引的轴长度一致

In [53]:
data[names == 'Bob', 2:]

array([[-1.02645167,  0.44442646],
       [-0.04506876,  1.13727669]])

In [54]:
data[names == 'Bob', 3]

array([0.44442646, 1.13727669])

In [55]:
#要选择除"Bob"以外的其他值，既可以使用不等于符号（!=），也可以通过~对条件进行否定：
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [56]:
data[~(names == 'Bob')]

array([[-0.05033314, -1.49198746, -1.89303973, -0.53393241],
       [ 0.51937743,  0.86376543, -0.04697297, -0.6856795 ],
       [ 0.2385302 ,  0.35767876,  0.45193206, -0.49099526],
       [-0.58349494, -0.57655013, -0.82805041, -0.16917763],
       [-0.12459374, -0.92308631,  2.35621205,  0.22692394]])

In [57]:
#~操作符用来反转条件很好用：
cond = names == 'Bob'
data[~cond]

array([[-0.05033314, -1.49198746, -1.89303973, -0.53393241],
       [ 0.51937743,  0.86376543, -0.04697297, -0.6856795 ],
       [ 0.2385302 ,  0.35767876,  0.45193206, -0.49099526],
       [-0.58349494, -0.57655013, -0.82805041, -0.16917763],
       [-0.12459374, -0.92308631,  2.35621205,  0.22692394]])

In [58]:
mask = (names == 'Bob') | (names == 'Will')

In [59]:
mask

array([ True, False,  True,  True,  True, False, False])

In [60]:
data[mask]

array([[ 1.24165116,  0.91849097, -1.02645167,  0.44442646],
       [ 0.51937743,  0.86376543, -0.04697297, -0.6856795 ],
       [-0.37949576, -1.02205427, -0.04506876,  1.13727669],
       [ 0.2385302 ,  0.35767876,  0.45193206, -0.49099526]])

In [61]:
###通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回一模一样的数组也是如此。
###Python关键字and和or在布尔型数组中无效。要使用&与|

In [62]:
#通过布尔型数组设置值是一种经常用到的手段。为了将data中的所有负值都设置为0，我们只需
data[data < 0] = 0

In [63]:
data

array([[1.24165116, 0.91849097, 0.        , 0.44442646],
       [0.        , 0.        , 0.        , 0.        ],
       [0.51937743, 0.86376543, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.13727669],
       [0.2385302 , 0.35767876, 0.45193206, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.35621205, 0.22692394]])

In [64]:
#通过一维布尔数组设置整行或列的值也很简单：
data[names != 'Joe'] = 7

In [65]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.35621205, 0.22692394]])

# 花式索引

In [66]:
#花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。假设我们有一个8×4数组：

In [67]:
arr = np.empty((8,4))

In [69]:
for i in range(8):
    arr[i] = i

In [70]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [71]:
arr[[4,3,0,6]]
#索引

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [72]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [73]:
#一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应各个索引元组：

In [74]:
arr = np.arange(32).reshape((8, 4))

In [75]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [76]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
#得到的是（1，0）（5，3）（7，1）（2，2）具体表示第一行第0列
###无论数组是多少维的，花式索引总是一维的。

array([ 4, 23, 29, 10])

In [77]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
###花式索引跟切片不一样，它总是将数据复制到新数组中。

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# 数组转置和轴对换

In [80]:
arr = np.arange(15).reshape((3,5))

In [81]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
arr.T
#数组的转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [83]:
arr = np.random.randn(6,3)

###np.random.rand()函数通过本函数可以返回一个或一组服从“0~1”均匀分布的随机样本值。随机样本取值范围是[0,1)，不包括1。
###np.random.randn()通过本函数可以返回一个或一组服从标准正态分布的随机样本值。

In [84]:
arr

array([[-0.051288  ,  1.66442223, -2.3199145 ],
       [-0.89701871,  0.10589717, -1.2653348 ],
       [-0.29109018, -0.58464663,  0.22195482],
       [ 0.64846792, -0.02863497,  2.65726178],
       [ 0.37496726, -0.17643046, -0.71676186],
       [-1.52088444, -0.69734559, -0.55697136]])

In [85]:
np.dot(arr.T,arr)
#x.dot(y) 等价于 np.dot(x,y) ———x是m*n 矩阵 ，y是n*m矩阵，则x.dot(y) 得到m*m矩阵。
#矩阵积计算不遵循交换律,np.dot(x,y) 和 np.dot(y,x) 得到的结果是不一样的。

array([[ 3.76620707,  0.96568582,  3.49087975],
       [ 0.96568582,  3.64156579, -3.68630823],
       [ 3.49087975, -3.68630823, 14.91734418]])