In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
x.dot(y)
#（2*3）*（3*2）

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x,y)
#x.dot(y)等价于np.dot(x, y)：
#但是dot(x, y)不等于dot(y, x)，因为矩阵乘法不满足交换律

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
#一个二维数组跟一个大小合适的一维数组的矩阵点积运算之后将会得到一个一维数组：
np.dot(x,np.ones(3))#ones(shape, dtype=None, order='C')

###x=（3*2）ones=(1*3)    疑问点？？？

array([ 6., 15.])

In [8]:
x @ np.ones(3)
#@符（类似Python 3.5）也可以用作中缀运算符，进行矩阵乘法：

array([ 6., 15.])

# 伪随机数生成

In [9]:
#numpy.random模块对Python内置的random进行了补充，增加了一些用于高效生成多种概率分布的样本值的函数。例如，你可以用normal来得到一个标准正态分布的4×4样本数组：

In [10]:
samples = np.random.normal(size=(4, 4))

In [11]:
samples

array([[-1.10841639,  1.54999096,  1.03537724, -2.02470517],
       [ 0.3326468 , -0.41464173,  0.21083863,  0.78176406],
       [-1.08155344, -1.0878678 , -0.35871809,  0.5833602 ],
       [-1.45512829,  2.330032  , -1.28063151,  1.63880597]])

In [12]:
#而Python内置的random模块则只能一次生成一个样本值。从下面的测试结果中可以看出，如果需要产生大量样本值，numpy.random快了不止一个数量级：

In [14]:
from random import normalvariate

In [15]:
N = 1000000
###省略两行不可运行的代码
#%timeit samples = [normalvariate(0, 1) for _ in range(N)]
1.77 s +- 126 ms per loop (mean +- std. dev. of 7 runs, 1 loop each)
# %timeit np.random.normal(size=N)
61.7 ms +- 1.32 ms per loop (mean +- std. dev. of 7 runs, 10 loops each)

In [17]:
#我们说这些都是伪随机数，是因为它们都是通过算法基于随机数生成器种子，在确定性的条件下生成的。你可以用NumPy的np.random.seed更改随机数生成种子：
np.random.seed(1234)

In [18]:
#numpy.random的数据生成函数使用了全局的随机种子。要避免全局状态，你可以使用numpy.random.RandomState，创建一个与其它隔离的随机数生成器：

In [19]:
 rng = np.random.RandomState(1234)

In [20]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])